name: Sync upstream

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync with upstream
        run: |
          gh repo sync mrsterner/Thaumaturge \
            --source Leclowndu93150/Thaumaturge \
            --branch main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
